apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: %FEATURE%test-kafka-avro
  namespace: %NAMESPACE%
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: %FEATURE%test-kafka-avro
        serverpod: %FEATURE%test-kafka-avro
    spec:
      imagePullSecrets:
      - name: cluster-registry-bluemix
      containers:
      - name: %FEATURE%test-kafka-avro
        image: %DOCKER_REGISTRY%/%DOCKER_REPOSITORY%/test-kafka-avro:%IMAGE_TAG%
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_DB_HOSTS
          value: "%FEATURE%document-ods-mongodb:27017"
        - name: MONGO_DB_NAME
          value: "document_ods_db"
        - name: MONGO_DB_USER
          value: "dbuser"
        - name: MONGO_DB_PASSWORD
          value: "sda123"
        - name: MONGO_DB_OPTIONS
          value: ""
        - name: S3_ENDPOINT
          value: "http://%FEATURE%document-ods-minio:9000"
        - name: S3_REGION
          value: ""
        - name: S3_ACCESS_KEY
          value: "sdase"
        - name: S3_SECRET_KEY
          value: "test1234"
        - name: S3_BUCKET
          value: "documents"
        - name: KAFKA_CONSUMER_DOCUMENT_ODS_EVENT_TOPIC
          value: "%FEATURE%document-ods-event-topic"
        - name: KAFKA_CONSUMER_DOCUMENT_ODS_EEROR_TOPIC
          value: "%FEATURE%document-ods-error-topic"
        - name: KAFKA_SECURITY_PROTOCOL
          value: SASL_SSL
        - name: KAFKA_BROKER_HOST_1
          value: "kafka01-prod01.messagehub.services.eu-de.bluemix.net"
        - name: KAFKA_BROKER_HOST_2
          value: "kafka02-prod01.messagehub.services.eu-de.bluemix.net"
        - name: KAFKA_BROKER_HOST_3
          value: "kafka03-prod01.messagehub.services.eu-de.bluemix.net"
        - name: KAFKA_BROKER_HOST_4
          value: "kafka04-prod01.messagehub.services.eu-de.bluemix.net"
        - name: KAFKA_BROKER_HOST_5
          value: "kafka05-prod01.messagehub.services.eu-de.bluemix.net"
        - name: KAFKA_BROKER_PORT
          value: '9093'
        - name: SECRET_KAFKA_USERNAME
          valueFrom:
            secretKeyRef:
              name: kafka-managed
              key: username
        - name: SECRET_KAFKA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kafka-managed
              key: password
        - name: SERVICE_NAME
          value: "%FEATURE%document-ods-service"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: %FEATURE%test-kafka-avro
  name: %FEATURE%test-kafka-avro
  namespace: %NAMESPACE%
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    serverpod: %FEATURE%test-kafka-avro
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: %FEATURE%test-kafka-avro
  namespace: %NAMESPACE%
spec:
  rules:
  - host: %URL%.intern.test.sda-se.com
    http:
      paths:
      - backend:
          serviceName: %FEATURE%test-kafka-avro
          servicePort: 8080
        path: /
  - host: minio.%URL%.intern.test.sda-se.com
    http:
      paths:
      - backend:
          serviceName: %FEATURE%document-ods-minio
          servicePort: 9000
        path: /
